# Generated by Django 2.0.5 on 2018-07-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='주문명')),
                ('amount', models.PositiveIntegerField(verbose_name='금액')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('buyer', models.CharField(blank=True, max_length=50, null=True, verbose_name='구매자명')),
                ('tel', models.CharField(max_length=100, verbose_name='구매자 연락처')),
                ('addr', models.CharField(blank=True, max_length=256, null=True, verbose_name='구매자 주소')),
                ('subaddr', models.CharField(blank=True, max_length=256, null=True, verbose_name='구매자 주소 나머지')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='구매자 우편번호')),
                ('pay_status', models.CharField(choices=[('ready', '결제 대기'), ('confirmed', '결제 완료')], default='ready', max_length=30, verbose_name='결제 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='주문명')),
                ('amount', models.PositiveIntegerField(verbose_name='금액')),
                ('uid', models.CharField(max_length=100, verbose_name='uid')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('buyer_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='구매자명')),
                ('buyer_tel', models.CharField(max_length=100, verbose_name='구매자 연락처')),
                ('buyer_addr', models.CharField(blank=True, max_length=256, null=True, verbose_name='구매자 주소')),
                ('buyer_postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='구매자 우편번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일자')),
                ('confirmed_at', models.DateTimeField(null=True, verbose_name='결제완료일자')),
                ('pay_result', models.CharField(choices=[('ready', '결제 대기'), ('success', '결제 성공'), ('failed', '결제 실패'), ('error', '비정상')], default='ready', max_length=30, verbose_name='결제 결과')),
                ('imp_uid', models.CharField(blank=True, max_length=50, null=True, verbose_name='승인번호')),
                ('imp_result', models.CharField(blank=True, max_length=512, null=True, verbose_name='결제결과')),
                ('pg_tid', models.CharField(blank=True, max_length=50, null=True, verbose_name='PG 승인번호')),
                ('card_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='카드승인번호')),
                ('receipt_url', models.URLField(blank=True, null=True, verbose_name='영수증 URL')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='myshop.Order')),
            ],
            options={
                'verbose_name': '제품 결제',
                'verbose_name_plural': '제품 결제 목록',
            },
        ),
    ]
